### ISSUE TITLE
Catching async API errors

### ISSUE THREAD

**Issue by jaganathanb** [sergiodxa/redux-catch#6]
Is it possible to catch the error which is thrown by an Async API? If so, Please provide an example.

**Comment by sergiodxa** [comment]
I tried with [redux-thunk](https://github.com/gaearon/redux-thunk) and not, this middleware can't catch errors in async action creators (and I suppose in any kind of async code executed in middlewares).

This is the code I used to try this, maybe you can find a way to use it, but I'm not sure it will work because the middleware is just a `try {} catch (error) {}`.
```js
import { applyMiddleware, createStore } from 'redux';
import reduxThunk from 'redux-thunk';
import reduxCatch from 'redux-catch';

function reducer(state = [], action = {}) {
  switch(action.type) {
    case 'ADD': {
      return state.concat(action.payload);
    }
    default: {
      return state;
    }
  }
}

function errorHandler(error, getState, lastAction) {
  console.error(error);
  console.debug('state', getState());
  console.debug('action', lastAction);
}

async function getPosts(dispatch) {
  throw new Error('test error');
  const data = ['hello', 'world'];
  dispatch({
    type: 'ADD',
    payload: data,
  });
}

const store = createStore(
  reducer,
  applyMiddleware(
    reduxThunk,
    reduxCatch(errorHandler)
  )
);

store.subscribe(() => {
  console.debug('state', store.getState());
});

store.dispatch(getPosts);
```

**Comment by jaganathanb** [comment]
Thanks for the update. Could you please update Readme.md with this.

**Comment by fantua** [comment]
Maybe my implementation of [redux-async-catch](https://github.com/fantua/redux-async-catch) will be helpful.
